Group/my collection
bkuhn2/Vinyl_Viewer pull request #2
Opened 2023-01-04 21:30 UTC by JPierce28

#### What does this PR do?
- This PR is for the MyCollection component. I created functional components and passed state down to be able to access a users saved albums. I applied wireframe css. 

#### What (if any) features are you implementing?
- The ability to view any saved albums a user has saved.
- The ability to filter through their saved albums but artist name.

#### What (if anything) did you refactor?
- Throughout my commits I refactored my own code to be cleaner and more efficient.

#### Were there any issues that arose?
- Learning how to pass props down and change state in typescript.

#### Any other comments, questions, or concerns?
- As the project progresses some changes may need to be made and some styling will most certainly need to be improved.

2023-01-04 23:05 UTC, sam-rice requested changes

2023-01-04 23:05 UTC, sam-rice commented on src/Components/UserCollection/UserCollection.tsx
> +          <div className='album-card'>
I think adding a `key` attribute here would take care of an error I'm getting in the console.

2023-01-04 23:05 UTC, sam-rice commented on src/Components/UserCollection/UserCollection.tsx
> +    }
You might want to consider conditionally rendering the "no albums" message and album collection instead of wrapping two separate returns in an `if` statement. I'm just thinking that if we need to make changes to something that stays the same in either case—the form, for instance—we won't have to change it in two places, and overall it might be easier to work with.

2023-01-04 23:05 UTC, sam-rice commented on src/Components/UserCollection/UserCollection.tsx
> +    }
I wasn't able to get the filter to to work, but it looks like the return statement on line 23 should be a `setCollection(myAlbums)` if I'm following your logic? (so that the entire collection coming in as a prop would be displayed when the filter input has no value) Since `filterAlbums()` is invoked from the button's `onClick`, I don't think returning anything will have an effect there or on line 29.

2023-01-04 23:05 UTC, sam-rice commented on src/Components/UserCollection/UserCollection.tsx
> +  const[filteredCollection, setCollection] = useState<AlbumsArray[]>(savedAlbums)
I think having this in state is a good approach for the filter!

2023-01-05 00:44 UTC, JPierce28 commented on src/Components/UserCollection/UserCollection.tsx
> +          <div className='album-card'>
Changed the UserCollection Component to instead render an AlbumCard that has the prop "key"

2023-01-05 00:45 UTC, JPierce28 commented on src/Components/UserCollection/UserCollection.tsx
> +    }
Changed this entirely. I am now conditionally rendering in the return of UserCollection component.

2023-01-05 00:47 UTC, JPierce28 commented on src/Components/UserCollection/UserCollection.tsx
> +    }
Cleaned this function up. I also added a "clear search filters" button and "clear inputs" function. When a user types any part of the artist they should see any albums that have saved with that artist. For example, if you only type "Heartbreakers" you should only see albums that include that artist. Pressing the clear search filters button will then reset the state to all of the users saved albums.

2023-01-05 00:47 UTC, JPierce28 commented on src/Components/UserCollection/UserCollection.tsx
> +  const[filteredCollection, setCollection] = useState<AlbumsArray[]>(savedAlbums)
Thank you!

2023-01-05 16:58 UTC, merged

2023-01-08 14:09 UTC, hfaerber commented on src/Components/UserCollection/UserCollection.tsx
> +          <div className='album-card'>
Love seeing this communication in the PR

2023-01-08 14:11 UTC, hfaerber commented
Really impressed with the thorough communication and thorough and productive code review and corresponding changes.  Great work!